title: Liam Tan
description: Mathematics PhD student at the University of Illinois Chicago.
logo: /assets/images/liam-photo.png
url: "https://liam-tan.github.io"
baseurl: ""
github_username: liam-tan
theme: jekyll-theme-minimal
show_downloads: false
plugins:
  - jekyll-feed
